### ISSUE TITLE
Docker is missing

### ISSUE THREAD

**Issue by annikahannig** [cccb/www#1]
Neither a Dockerfile, nor a docker-compose.yml could be found.
This is unacceptable in a modern webdev environment. 

I'm at a loss. I have no clue on how to run or deploy this.
Can someone please fix this?

Keep up the good work!

**Comment by fuu0** [comment]
We will deploy soon our kubernetes Cluster with CephOS Storage - after that and after creating 420 Jenkins Integration Tests we can hope that our copy&paste dockerfile starts! Just some clicks, and also the cloudflare Protection is ready...
